:PROPERTIES:
:ID:       e9d57b8a-ac31-490a-9e31-2cbfa65ac836
:END:
#+title: booting
#+date: [2024-09-17 Tue 08:12]
#+startup: overview


https://wiki.debian.org/BootLoader#Debian_default_boot_loaders

* Booting
** 1. BIOS/UEFI Initialization
[[https://en.wikipedia.org/wiki/BIOS]]
- *BIOS/UEFI Initialization*:
  - When you power on the computer, the BIOS (Basic Input/Output System) or UEFI (Unified Extensible Firmware Interface) performs hardware initializations and system checks.
- It then searches for a bootloader in the configured boot device (like a hard disk, SSD, USB drive, etc.).
** 2. Loading GRUB
- *Finding GRUB*: The BIOS/UEFI locates the Master Boot Record (MBR) or the GUID Partition Table (GPT) where GRUB is installed.
- *Executing GRUB*: It loads GRUB into memory and transfers control to it.

** 3. GRUB Initialization
- *Stage 1*: GRUB Stage 1 or the initial part of GRUB is minimal and might just point to the next stage – Stage 1.5 or Stage 2.
- *Stage 1.5*: This stage is optional and may provide support for reading from the filesystem where Stage 2 resides.
- *Stage 2*: GRUB Stage 2 is capable of reading the filesystem and loading required modules. It displays the GRUB menu to the user.

** 4. GRUB Menu
- The GRUB menu is where you select an operating system or kernel to boot.
- It lists all the configured boot entries, such as different kernels, recovery modes, or other operating systems installed.

** 5. Loading the Kernel
- *Selecting an Entry*: When you select an option from the GRUB menu, GRUB loads the corresponding kernel and the initial RAM disk (initrd/initramfs) into memory.
- *Boot Parameters*: GRUB passes any necessary boot parameters to the kernel.
- *Transferring Control*: Finally, GRUB hands over control to the kernel.

** 6. Kernel Initialization
- *Loading Kernel Modules*: The kernel initializes itself and loads necessary modules and drivers.
- *Mounting Root Filesystem*: The kernel mounts the root filesystem specified in the boot parameters.
** 7. Init System
- *Initrd/Initramfs*: The initial RAM disk mounts the real root filesystem and executes the initial system initialization process.
- *[[id:040f1e6f-4bad-411a-9a9c-60a48d123bfa][Systemd]]/SysVinit*: Depending on the initialization system (like systemd or SysVinit), the init process takes over, starting essential services and setting up the user environment.
** 8. User Space
- *Login*: Eventually, the system displays a login prompt or a graphical login screen if a display manager is configured.
- *User Environment*: After logging in, the user is presented with the shell or desktop environment.
* GRUB
*GRand Unified Bootloader*
https://wiki.archlinux.org/title/GRUB#Configuration

- designed to boot a wide variety of operating systems, primarily Unix-like systems.
- allows users to select and boot different operating systems or kernels installed on a system at boot time
- highly configurable
- supports various file systems
** How do I configure grub?

Configuring GRUB involves editing its configuration file and then updating the GRUB configuration.

1. *Edit the Configuration File:*
   - typically located in the =/boot/grub= or =/boot/grub2= directories
   - The main configuration file is usually named =grub.cfg=:
   #+begin_src sh
   sudo nano /etc/default/grub
   #+end_src

2. *Make Necessary Changes:*
   - Modify the settings according to your needs
     - default boot entry, timeout, and background image
   - Common variables include =GRUB_TIMEOUT=, =GRUB_DEFAULT=, and =GRUB_CMDLINE_LINUX=

3. *Update GRUB:*
   After making the changes, save the file and update the GRUB configuration to apply the changes:
   #+begin_src sh
   sudo update-grub
   #+end_src

4. *Reboot:*
   Restart your computer to see the changes take effect:
   #+begin_src sh
   sudo reboot
   #+end_src

** Where is Grub installed?

- Master Boot Record (MBR) - BIOS
- EFI System Partition (ESP) of a disk - UEFI
- *MBR (for BIOS systems):* GRUB is installed in the first 512 bytes of the disk. This is the MBR area, which is loaded by the BIOS and then GRUB handles the rest of the boot process.
- *EFI System Partition (for UEFI systems):* GRUB is installed in a special partition formatted with a FAT file system, commonly referred to as the EFI System Partition (ESP). The path is usually:
