:PROPERTIES:
:ID:       b9739fc8-02f8-4e5b-94d1-ea0816fd22ee
:END:
#+title: authentication and access controls
#+date: [2024-09-17 Tue 16:41]
#+startup: overview

https://www.debian.org/doc/manuals/debian-reference/ch04.en.html

* [[id:8b70efb6-c0b2-4beb-b9c2-6672cfbe3f70][sudo]]
* [[id:96f8cc1f-e5fe-408a-84f0-90a9b0b8878b][PAM (pluggable authentication modules)]]
* [[id:9195cabf-21d7-42fb-bb12-b20e83f888dc][/etc/shadow]]
* [[id:13126145-0f4a-4901-aa9a-3e76d3ada7f5][/etc/login.defs]]
* [[id:5cce0070-5955-476b-a029-f719517f93cd][libpam-pwquality]]

* changing passwords
:PROPERTIES:
:ID:       bad3febb-0374-4018-a727-e5e2bc73cef2
:END:
- change with passwd command
* commands
** expiry
https://manpages.debian.org/bookworm/passwd/expiry.1.en.html
** chage (change age)
:PROPERTIES:
:ID:       f567a019-1852-430e-859b-7d320a8a8cd9
:END:
=sudo chage -l username==
- [ ] expiration every 30 days (maximum password age)
  - -M, --maxdays MAX_DAYS
- [ ] minimum nbr of days allowed before modification = 2 (minimum password age)
  - -m, --mindays MIN_DAYS
- [ ] user receives a warning message 7 days before their password expires
  - -W, --warndays WARN_DAYS
*** applying changes to already existing users
=sudo chage --maxdays 30 kfreyer42=
=sudo chage --mindays 1 <username>=
=sudo chage --warndays 7 <username>=
** getent
"get entries from administrative database"
=getent group group_name=

* why do we choose to implement a strong password policy?
:PROPERTIES:
:ID:       83c2bee7-c27e-4685-b323-f16ab7200da5
:END:

Implementing a strong password policy is crucial for several reasons:

1. *Security*: Strong passwords help protect against unauthorized access to systems and sensitive data by making it more difficult for attackers to guess or crack passwords using automated tools.

2. *Data Protection*: Complex passwords reduce the risk of data breaches, which can result in data loss, theft, or corruption, affecting both individuals and organizations.

3. *Regulatory Compliance*: Many industries have regulations and standards that require strong password policies to ensure the protection of sensitive information (e.g., HIPAA for healthcare, PCI DSS for payment systems).

4. *Reduce the Risk of Exploits*: Strong passwords help mitigate the risk of credential-stuffing attacks, where attackers use compromised password databases from other sites to gain access.

5. *User Accountability*: By enforcing unique, strong passwords, organizations can ensure that access to critical systems is traceable and that users are accountable for their activities.

6. *Prevention of Identity Theft*: Strong passwords help safeguard personal information, minimizing the risk of identity theft.

Overall, a strong password policy is a fundamental component of a comprehensive security strategy to protect both users and organizations from cyber threats.
