:PROPERTIES:
:ID:       97a4f12c-6a42-4a82-bf9e-39c9dea7ac56
:END:
#+title: profile.d
#+date: [2024-11-18 Mo 15:55]
#+startup: overview

The =/etc/profile.d= directory is used on Unix-like systems to store shell script files that are sourced when a user logs in. These scripts are typically used to set environment variables and configure other settings related to the user's shell environment.


Files in this directory are executed as part of the system-wide user initialization process. When a user logs in, the shell reads and executes commands from the =/etc/profile= file, if it exists. This file may, in turn, source any scripts in =/etc/profile.d=, thus allowing for modular configuration by dividing different settings into separate files.

This mechanism makes it easy to manage environment settings across the system, as these scripts can be used to configure system-wide environment settings without modifying the main =/etc/profile= file directly.

[[id:76d882e5-2492-4b30-b7da-128b4dbb7fdc][adding /sbin to PATH]]
